### ISSUE TITLE
查询支持 not equal 

### ISSUE THREAD

**Issue by luoxy123** [FeiniuBus/SqlExecutor#5]
.netcore 版本和 golang 版本都查询支持 not equal

**Comment by ah-its-andy** [comment]
* 增加了新的参数组语义：`AndNot` 和 `OrNot` 用于表示应以 `false` 判定此参数组的语义。
* e.g. 
   * `builder.ParamGroupBuilder.CreateChild`**AndNot**`Group().ParamBuilder.Equal("Guest", "Andy")` 表示`Guest`不等于`Andy`，同时还表达 `And` 语义
  * `builder.ParamGroupBuilder.CreateChild`**OrNot**`Group().ParamBuilder.In("Drink", "mileshake,coffee")`  表示 `Drink` 不包含在 `mileshake,coffee` 中， 同时还表达 `Or` 语义

* ref :
   * [2.1.0-pre@SqlExecutor](//github.com/FeiniuBus/SqlExecutor/releases/tag/2.1.0-pre)
   * [1.1.0@SqlExecutor-Go](//github.com/FeiniuBus/SqlExecutor-Go/releases/tag/1.1.0)

@luoxy123
